source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'PixErfTest-Instagram' do
	pod 'OAuthSwift', '~> 0.5.0'
	pod 'SwiftyJSON’
	pod 'Alamofire', '~> 3.0’
    pod 'AlamofireImage', '~> 2.0'
    pod 'MBProgressHUD', '~> 0.9.2'
end

target 'PixErfTest-InstagramTests' do

end

target 'PixErfTest-InstagramUITests' do

end

